"use client";
import { ChangeEvent,useEffect,useRef,useState } from "react";
import Link from "next/link";
import { preparePhoto } from "./photo-processing";
import { readState,subscribeTables,supabase } from "./supabase";
import { submitWithRetry } from "./retry-submit";

export default function UploadPage(){
 const inputRef=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[status,setStatus]=useState<"idle"|"preparing"|"sending"|"sent">("idle"),[state,setState]=useState({display_mode:"none",questions_enabled:false,locale:"ko"});const en=state.locale==="en";
 useEffect(()=>{let alive=true;const refresh=()=>readState().then(v=>alive&&setState(v)).catch(()=>undefined);void refresh();const off=subscribeTables(refresh,["exhibit_state"]);const backup=setInterval(refresh,15000);return()=>{alive=false;off();clearInterval(backup);};},[]);
 function choose(e:ChangeEvent<HTMLInputElement>){const next=e.target.files?.[0]??null;if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(next?URL.createObjectURL(next):null);setStatus("idle");}
 async function send(){if(!file)return;setStatus("preparing");const id=crypto.randomUUID(),photoPath=`photos/${id}.jpg`,thumbPath=`thumbnails/${id}.jpg`;try{const prepared=await preparePhoto(file);setStatus("sending");const uploadOne=(path:string,blob:Blob)=>submitWithRetry(async()=>await supabase.storage.from("workshop-photos").upload(path,blob,{contentType:"image/jpeg",cacheControl:"31536000"}));await Promise.all([uploadOne(photoPath,prepared.main),uploadOne(thumbPath,prepared.thumbnail)]);await submitWithRetry(async()=>await supabase.from("photos").insert({id,storage_path:photoPath,thumbnail_path:thumbPath}));setStatus("sent");setFile(null);if(preview)URL.revokeObjectURL(preview);setPreview(null);if(inputRef.current)inputRef.current.value="";}catch{setStatus("idle");}}
 return <main className="upload-page"><section className="upload-card"><input ref={inputRef} className="visually-hidden" id="photo" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={choose}/>{preview?<button className="preview-button" onClick={()=>inputRef.current?.click()}><img src={preview} alt={en?"Selected photo":"선택한 사진"}/><span>{en?"Choose another photo":"다른 사진 선택"}</span></button>:<label className="pick-button" htmlFor="photo"><span className="plus">＋</span>{en?"Choose from photo library":"사진첩에서 선택"}</label>}<button className="send-button" onClick={send} disabled={!file||status==="preparing"||status==="sending"}>{status==="preparing"?(en?"Preparing photo…":"사진 준비 중…"):status==="sending"?(en?"Sending…":"보내는 중…"):(en?"Send to screen":"스크린으로 보내기")}</button><div className="status" aria-live="polite">{status==="sent"&&<p className="success">☺</p>}</div><Link className="wall-link" href="/gallery">{en?"View shared photo album":"공동 사진첩 목록 보기"}</Link>{state.questions_enabled?<Link className="sentence-link" href="/question">{en?"2. Ask a question":"2. 질문하기"}</Link>:<button className="sentence-link disabled" disabled>{en?"2. Ask a question":"2. 질문하기"}</button>}{state.display_mode==="play"?<Link className="path-link" href="/respond">{en?"3. Choose a question":"3. 질문 선택하기"}</Link>:<button className="path-link disabled" disabled>{en?"3. Choose a question":"3. 질문 선택하기"}</button>}</section></main>;
}
