'use client';
import { ChangeEvent,useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import { useExhibitState,useSubmission,SubmissionStatus } from './workshop-client';
export default function UploadPage(){
 const inputRef=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null);const state=useExhibitState(),submission=useSubmission('photo'),en=state.locale==='en';
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 function choose(e:ChangeEvent<HTMLInputElement>){const next=e.target.files?.[0]??null;setFile(next);setPreview(next?URL.createObjectURL(next):null);submission.reset();}
 async function send(){if(!file)return;if(await submission.submit({file})){setFile(null);setPreview(null);if(inputRef.current)inputRef.current.value='';}}
 return <main className="upload-page"><section className="upload-card"><input ref={inputRef} disabled={submission.busy} className="visually-hidden" id="photo" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={choose}/>{preview?<button className="preview-button" disabled={submission.busy} onClick={()=>inputRef.current?.click()}><img src={preview} alt={en?'Selected photo':'선택한 사진'}/><span>{en?'Choose another photo':'다른 사진 선택'}</span></button>:<label className="pick-button" htmlFor="photo"><span className="plus">＋</span>{en?'Choose from photo library':'사진첩에서 선택'}</label>}<button className="send-button" onClick={send} disabled={!file||submission.busy}>{submission.busy?(en?'Waiting to send…':'전송 대기 중…'):(en?'Send to screen':'스크린으로 보내기')}</button><SubmissionStatus state={submission.state} en={en}/><Link className="wall-link" href="/gallery">{en?'View shared photo album':'공동 사진첩 목록 보기'}</Link>{state.questions_enabled?<Link className="sentence-link" href="/question">{en?'2. Ask a question':'2. 질문하기'}</Link>:<button className="sentence-link disabled" disabled>{en?'2. Ask a question':'2. 질문하기'}</button>}{state.display_mode==='play'?<Link className="path-link" href="/respond">{en?'3. Choose a question':'3. 질문 선택하기'}</Link>:<button className="path-link disabled" disabled>{en?'3. Choose a question':'3. 질문 선택하기'}</button>}</section></main>;
}
