"use client";
import { ChangeEvent,useEffect,useRef,useState } from "react";
import Link from "next/link";
import { preparePhoto } from "./photo-processing";
import { readState,subscribeTables,supabase } from "./supabase";

export default function UploadPage(){
 const inputRef=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[status,setStatus]=useState<"idle"|"preparing"|"sending"|"sent"|"error">("idle"),[message,setMessage]=useState(""),[state,setState]=useState({display_mode:"none",questions_enabled:false});
 useEffect(()=>{let alive=true;const refresh=()=>readState().then(v=>alive&&setState(v)).catch(()=>undefined);void refresh();const off=subscribeTables(refresh,["exhibit_state"]);const backup=setInterval(refresh,15000);return()=>{alive=false;off();clearInterval(backup);};},[]);
 function choose(e:ChangeEvent<HTMLInputElement>){const next=e.target.files?.[0]??null;if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(next?URL.createObjectURL(next):null);setStatus("idle");setMessage("");}
 async function send(){if(!file)return;setStatus("preparing");const id=crypto.randomUUID(),photoPath=`photos/${id}.jpg`,thumbPath=`thumbnails/${id}.jpg`;try{const prepared=await preparePhoto(file);setStatus("sending");const uploadOne=async(path:string,blob:Blob)=>{const {error}=await supabase.storage.from("workshop-photos").upload(path,blob,{contentType:"image/jpeg",cacheControl:"31536000"});if(error)throw error;};await Promise.all([uploadOne(photoPath,prepared.main),uploadOne(thumbPath,prepared.thumbnail)]);const {error}=await supabase.from("photos").insert({storage_path:photoPath,thumbnail_path:thumbPath});if(error)throw error;setStatus("sent");setFile(null);if(preview)URL.revokeObjectURL(preview);setPreview(null);if(inputRef.current)inputRef.current.value="";}catch(e){await supabase.storage.from("workshop-photos").remove([photoPath,thumbPath]);setStatus("error");setMessage(e instanceof Error?e.message:"전송하지 못했습니다. 다시 시도해주세요.");}}
 return <main className="upload-page"><section className="upload-card"><input ref={inputRef} className="visually-hidden" id="photo" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={choose}/>{preview?<button className="preview-button" onClick={()=>inputRef.current?.click()}><img src={preview} alt="선택한 사진"/><span>다른 사진 선택</span></button>:<label className="pick-button" htmlFor="photo"><span className="plus">＋</span>사진첩에서 선택</label>}<button className="send-button" onClick={send} disabled={!file||status==="preparing"||status==="sending"}>{status==="preparing"?"사진 준비 중…":status==="sending"?"보내는 중…":"스크린으로 보내기"}</button><div className="status" aria-live="polite">{status==="sent"&&<p className="success">☺</p>}{status==="error"&&<p className="error">{message}</p>}</div><Link className="wall-link" href="/gallery">공동 사진첩 목록 보기</Link>{state.questions_enabled?<Link className="sentence-link" href="/question">2. 질문하기</Link>:<button className="sentence-link disabled" disabled>2. 질문하기</button>}{state.display_mode==="play"?<Link className="path-link" href="/respond">3. 질문 선택하기</Link>:<button className="path-link disabled" disabled>3. 질문 선택하기</button>}</section></main>;
}
