"use client";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import type { PointerEvent as ReactPointerEvent } from "react";
import { QRCodeSVG } from "qrcode.react";
import { adminStorage,publicPhotoUrl,readState,subscribeTables,supabase } from "../supabase";
type Mode="none"|"photos"|"play";type Pos={x:number;y:number;z:number};
type Photo={id:string;storage_path:string;thumbnail_path:string;created_at:string;x:number|null;y:number|null;z:number|null};
type Question={id:string;text:string;created_at:string;x:number|null;y:number|null;z:number|null};
type Response={id:string;question_id:string;photo_id:string;text:string;created_at:string;x:number|null;y:number|null;z:number|null};
type Drag={kind:"photo"|"question"|"response";id:string;dx:number;dy:number};
const MOBILE_URL="https://suspiciouscloudgames.github.io/ma/";
export default function GalleryPage(){
 const [mode,setMode]=useState<Mode>("none"),[questionsEnabled,setQuestionsEnabled]=useState(false),[photos,setPhotos]=useState<Photo[]>([]),[questions,setQuestions]=useState<Question[]>([]),[responses,setResponses]=useState<Response[]>([]),[qr,setQr]=useState(false),[busy,setBusy]=useState(false);const canvas=useRef<HTMLElement>(null),drag=useRef<Drag|null>(null);const [tick,setTick]=useState(0);
 const load=useCallback(async()=>{const [s,p,q,r]=await Promise.all([readState(),supabase.from("photos").select("*").order("created_at"),supabase.from("questions").select("*").order("created_at"),supabase.from("responses").select("*").order("created_at")]);setMode(s.display_mode);setQuestionsEnabled(s.questions_enabled);setPhotos((p.data??[])as Photo[]);setQuestions((q.data??[])as Question[]);setResponses((r.data??[])as Response[]);},[]);
 useEffect(()=>{void load();const off=subscribeTables(load,["exhibit_state","photos","questions","responses"]);const backup=setInterval(load,15000);return()=>{off();clearInterval(backup);};},[load]);
 const pos=(item:{x:number|null;y:number|null;z:number|null},i:number,kind:Drag["kind"]):Pos=>item.x!=null&&item.y!=null?{x:item.x,y:item.y,z:item.z??i+1}:kind==="photo"?{x:(i%4)*25.2,y:30+Math.floor(i/4)*350,z:i+1}:{x:kind==="question"?5:58,y:80+i*330,z:i+1};
 function admin(){let key=sessionStorage.getItem("ma-admin")??"";if(!key)key=prompt("관리자 암호를 입력하세요.")?.trim()??"";return key;}
 async function setState(next:{mode?:Mode;questions?:boolean}){const key=admin();if(!key)return;setBusy(true);const {data,error}=await supabase.rpc("admin_set_state",{admin_key:key,next_display_mode:next.mode??mode,next_questions_enabled:next.questions??questionsEnabled,next_locale:"ko"});setBusy(false);if(error){sessionStorage.removeItem("ma-admin");alert("관리자 암호가 맞지 않습니다.");return;}sessionStorage.setItem("ma-admin",key);setMode(data.display_mode);setQuestionsEnabled(data.questions_enabled);}
 function start(e:ReactPointerEvent<HTMLElement>,kind:Drag["kind"],id:string){if(innerWidth<=760||(e.target as HTMLElement).closest("button"))return;const c=canvas.current;if(!c)return;e.preventDefault();const r=e.currentTarget.getBoundingClientRect();drag.current={kind,id,dx:e.clientX-r.left,dy:e.clientY-r.top};e.currentTarget.setPointerCapture(e.pointerId);}
 function moving(e:ReactPointerEvent<HTMLElement>){if(!drag.current||!canvas.current)return;const c=canvas.current.getBoundingClientRect(),r=e.currentTarget.getBoundingClientRect();const x=Math.max(0,Math.min(100-r.width/c.width*100,(e.clientX-c.left-drag.current.dx)/c.width*100)),y=Math.max(0,e.clientY-c.top-drag.current.dy);const apply=<T extends {id:string;x:number|null;y:number|null;z:number|null}>(xs:T[])=>xs.map(v=>v.id===drag.current?.id?{...v,x,y,z:999}:v);if(drag.current.kind==="photo")setPhotos(apply(photos));else if(drag.current.kind==="question")setQuestions(apply(questions));else setResponses(apply(responses));setTick(v=>v+1);}
 async function finish(){const d=drag.current;if(!d)return;drag.current=null;const list=d.kind==="photo"?photos:d.kind==="question"?questions:responses;const item=list.find(v=>v.id===d.id);const key=admin();if(!item||!key)return;const {error}=await supabase.rpc("admin_move_item",{admin_key:key,item_kind:d.kind,item_id:d.id,next_x:item.x,next_y:item.y,next_z:item.z??999});if(error)alert("위치를 저장하지 못했습니다.");else sessionStorage.setItem("ma-admin",key);}
 async function remove(kind:Drag["kind"],id:string){if(!confirm("삭제할까요?"))return;const key=admin();if(!key)return;if(kind==="photo"){const p=photos.find(v=>v.id===id);if(p){const {error}=await adminStorage(key).storage.from("workshop-photos").remove([p.storage_path,p.thumbnail_path]);if(error){sessionStorage.removeItem("ma-admin");alert("관리자 암호가 맞지 않거나 사진을 삭제하지 못했습니다.");return;}}}const {error}=await supabase.rpc("admin_delete_item",{admin_key:key,item_kind:kind,item_id:id});if(error){alert("삭제하지 못했습니다.");return;}sessionStorage.setItem("ma-admin",key);void load();}
 const photoMap=useMemo(()=>new Map(photos.map(p=>[p.id,p])),[photos]);const height=Math.max(700,...photos.map((p,i)=>pos(p,i,"photo").y+360),...questions.map((q,i)=>pos(q,i,"question").y+300),...responses.map((r,i)=>pos(r,i,"response").y+300));
 useEffect(()=>{const on=()=>setTick(v=>v+1);addEventListener("resize",on);return()=>removeEventListener("resize",on);},[]);
 const lines=useMemo(()=>{if(mode!=="play"||!canvas.current)return[];const cr=canvas.current.getBoundingClientRect();return responses.map(r=>{const a=document.querySelector(`[data-q="${r.question_id}"]`)?.getBoundingClientRect(),b=document.querySelector(`[data-r="${r.id}"]`)?.getBoundingClientRect();if(!a||!b)return null;const x1=a.left+a.width/2-cr.left,y1=a.top+a.height/2-cr.top,x2=b.left+b.width/2-cr.left,y2=b.top+b.height/2-cr.top;return{id:r.id,x1,y1,x2,y2};}).filter(Boolean)as {id:string;x1:number;y1:number;x2:number;y2:number}[];},[mode,questions,responses,tick]);
 return <main className="gallery-page exhibit-page"><header className="gallery-header exhibit-header"><div className="gallery-title"><h1>모바일 고고학</h1><p>사진을 길게 눌러 선택하고 저장하세요.</p></div><Link className="gallery-back" href="/">돌아가기</Link><div className="exhibit-controls"><div className="exhibit-modes"><button className={mode==="photos"?"active":""} disabled={busy} onClick={()=>setState({mode:mode==="photos"?"none":"photos"})}>1. 모바일 고고학</button><button className={questionsEnabled?"active":""} disabled={busy} onClick={()=>setState({questions:!questionsEnabled})}>2. 질문</button><button className={mode==="play"?"active":""} disabled={busy} onClick={()=>setState({mode:mode==="play"?"none":"play"})}>3. 기척의 놀이</button></div></div><button className="gallery-qr" onClick={()=>setQr(true)}><QRCodeSVG value={MOBILE_URL}/></button></header>
 {qr&&<button className="qr-overlay" onClick={()=>setQr(false)}><QRCodeSVG value={MOBILE_URL}/></button>}
 {mode==="none"&&<div className="gallery-empty"/>}
 <section ref={canvas} className="gallery-grid exhibit-canvas" style={{minHeight:height,display:mode==="none"?"none":undefined}}>{mode==="play"&&<svg className="gallery-connections" width="100%" height={height}>{lines.map(l=><line key={l.id} x1={l.x1} y1={l.y1} x2={l.x2} y2={l.y2}/>)}</svg>}
 {mode==="photos"&&photos.map((p,i)=>{const v=pos(p,i,"photo");return <article key={p.id} className="gallery-item" style={{left:`${v.x}%`,top:v.y,zIndex:v.z}} onPointerDown={e=>start(e,"photo",p.id)} onPointerMove={moving} onPointerUp={finish}><div className="photo-actions"><button onClick={()=>remove("photo",p.id)}>×</button></div><img src={publicPhotoUrl(p.storage_path)} alt="공동 사진"/></article>;})}
 {mode==="play"&&questions.map((q,i)=>{const v=pos(q,i,"question");return <article data-q={q.id} key={q.id} className="question-node" style={{left:`${v.x}%`,top:v.y,zIndex:v.z}} onPointerDown={e=>start(e,"question",q.id)} onPointerMove={moving} onPointerUp={finish}><button className="node-delete" onClick={()=>remove("question",q.id)}>×</button><span>{q.text}</span></article>;})}
 {mode==="play"&&responses.map((r,i)=>{const v=pos(r,i,"response"),p=photoMap.get(r.photo_id);return <article data-r={r.id} key={r.id} className="question-response-node" style={{left:`${v.x}%`,top:v.y,zIndex:v.z}} onPointerDown={e=>start(e,"response",r.id)} onPointerMove={moving} onPointerUp={finish}><button className="node-delete" onClick={()=>remove("response",r.id)}>×</button>{p&&<img src={publicPhotoUrl(p.storage_path)} alt="연결된 사진"/>}<p>{r.text}</p></article>;})}</section>
 <section className="mobile-photo-list">{photos.map(p=><img key={p.id} src={publicPhotoUrl(p.storage_path)} alt="공동 사진"/>)}</section></main>;
}
