"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { participantId } from "../participant-id";
import { publicPhotoUrl,readState,subscribeTables,supabase } from "../supabase";
import { submitWithRetry } from "../retry-submit";
type Q={id:string;text:string};type P={id:string;thumbnail_path:string};
export default function RespondPage(){
 const [step,setStep]=useState<1|2|3>(1),[enabled,setEnabled]=useState(false),[locale,setLocale]=useState<"ko"|"en">("ko"),[questions,setQuestions]=useState<Q[]>([]),[photos,setPhotos]=useState<P[]>([]),[qid,setQid]=useState<string|null>(null),[text,setText]=useState(""),[pid,setPid]=useState<string|null>(null),[status,setStatus]=useState("idle");const en=locale==="en";
 useEffect(()=>{let alive=true;const load=async()=>{const [s,q,p]=await Promise.all([readState(),supabase.from("questions").select("id,text").order("created_at"),supabase.from("photos").select("id,thumbnail_path").order("created_at")]);if(alive){setEnabled(s.display_mode==="play");setLocale(s.locale);setQuestions((q.data??[])as Q[]);setPhotos((p.data??[])as P[]);}};void load();const off=subscribeTables(load,["exhibit_state","questions","photos"]);return()=>{alive=false;off();};},[]);
 async function submit(){if(!qid||!pid||!text.trim())return;setStatus("sending");const id=crypto.randomUUID();try{await submitWithRetry(async()=>await supabase.from("responses").insert({id,question_id:qid,photo_id:pid,text:text.trim(),participant_id:participantId()}));setStatus("sent");}catch{setStatus("idle");}}
 if(status==="sent")return <main className="connect-page"><section className="connect-card connect-finished"><div>☺</div><Link href="/">{en?"Back":"돌아가기"}</Link></section></main>;
 if(!enabled)return <main className="connect-page"><section className="connect-card connect-finished"><p>{en?"Question selection is not open right now.":"지금은 질문 선택이 열려 있지 않아요."}</p><Link href="/">{en?"Back":"돌아가기"}</Link></section></main>;
 return <main className="connect-page"><section className="connect-card"><header className="connect-header"><span>{step} / 3</span><Link href="/">{en?"Close":"닫기"}</Link></header>{step===1&&<><h1>{en?"Choose a question.":"질문을 선택하세요."}</h1><div className="question-choice-list">{questions.map(q=><button key={q.id} className={qid===q.id?"selected":""} onClick={()=>setQid(q.id)}>{q.text}</button>)}</div><button className="connect-next" disabled={!qid} onClick={()=>setStep(2)}>{en?"Next":"다음"}</button></>}{step===2&&<><h1>{en?"Write a sentence.":"문장을 입력하세요."}</h1><p className="connect-sentence">{questions.find(q=>q.id===qid)?.text}</p><textarea value={text} onChange={e=>setText(e.target.value)} autoFocus/><div className="connect-footer"><button onClick={()=>setStep(1)}>{en?"Back":"이전"}</button><button disabled={!text.trim()} onClick={()=>setStep(3)}>{en?"Choose photo":"사진 선택"}</button></div></>}{step===3&&<><h1>{en?"Choose a photo.":"사진을 선택하세요."}</h1><div className="connect-photos">{photos.map(p=><button key={p.id} className={pid===p.id?"selected":""} onClick={()=>setPid(p.id)}><img src={publicPhotoUrl(p.thumbnail_path)} alt={en?"Shared photo":"공동 사진"}/></button>)}</div><div className="connect-footer"><button onClick={()=>setStep(2)}>{en?"Back":"이전"}</button><button disabled={!pid||status==="sending"} onClick={submit}>{status==="sending"?(en?"Sending…":"보내는 중…"):(en?"Send together":"함께 보내기")}</button></div></>}</section></main>;
}
