"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { participantId } from "../participant-id";
import { publicPhotoUrl,readState,subscribeTables,supabase } from "../supabase";
type Q={id:string;text:string};type P={id:string;thumbnail_path:string};
export default function RespondPage(){
 const [step,setStep]=useState<1|2|3>(1),[enabled,setEnabled]=useState(false),[questions,setQuestions]=useState<Q[]>([]),[photos,setPhotos]=useState<P[]>([]),[qid,setQid]=useState<string|null>(null),[text,setText]=useState(""),[pid,setPid]=useState<string|null>(null),[status,setStatus]=useState("idle");
 useEffect(()=>{let alive=true;const load=async()=>{const [s,q,p]=await Promise.all([readState(),supabase.from("questions").select("id,text").order("created_at"),supabase.from("photos").select("id,thumbnail_path").order("created_at")]);if(alive){setEnabled(s.display_mode==="play");setQuestions((q.data??[])as Q[]);setPhotos((p.data??[])as P[]);}};void load();const off=subscribeTables(load,["exhibit_state","questions","photos"]);return()=>{alive=false;off();};},[]);
 async function submit(){if(!qid||!pid||!text.trim())return;setStatus("sending");const {error}=await supabase.from("responses").insert({question_id:qid,photo_id:pid,text:text.trim(),participant_id:participantId()});setStatus(error?"error":"sent");}
 if(status==="sent")return <main className="connect-page"><section className="connect-card connect-finished"><div>☺</div><Link href="/">돌아가기</Link></section></main>;
 if(!enabled)return <main className="connect-page"><section className="connect-card connect-finished"><p>지금은 질문 선택이 열려 있지 않아요.</p><Link href="/">돌아가기</Link></section></main>;
 return <main className="connect-page"><section className="connect-card"><header className="connect-header"><span>{step} / 3</span><Link href="/">닫기</Link></header>{step===1&&<><h1>질문을 선택하세요.</h1><div className="question-choice-list">{questions.map(q=><button key={q.id} className={qid===q.id?"selected":""} onClick={()=>setQid(q.id)}>{q.text}</button>)}</div><button className="connect-next" disabled={!qid} onClick={()=>setStep(2)}>다음</button></>}{step===2&&<><h1>문장을 입력하세요.</h1><p className="connect-sentence">{questions.find(q=>q.id===qid)?.text}</p><textarea value={text} onChange={e=>setText(e.target.value)} autoFocus/><div className="connect-footer"><button onClick={()=>setStep(1)}>이전</button><button disabled={!text.trim()} onClick={()=>setStep(3)}>사진 선택</button></div></>}{step===3&&<><h1>사진을 선택하세요.</h1><div className="connect-photos">{photos.map(p=><button key={p.id} className={pid===p.id?"selected":""} onClick={()=>setPid(p.id)}><img src={publicPhotoUrl(p.thumbnail_path)} alt="공동 사진"/></button>)}</div><div className="connect-footer"><button onClick={()=>setStep(2)}>이전</button><button disabled={!pid||status==="sending"} onClick={submit}>{status==="sending"?"보내는 중…":"함께 보내기"}</button></div></>}{status==="error"&&<p className="connect-error">전송하지 못했어요. 다시 시도해주세요.</p>}</section></main>;
}
